
services:
  db:
    image: postgres:15-alpine
    container_name: obmep_bd
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: incubos123
      POSTGRES_DB: olimpiadas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: